EventMenegmentUser/Controllers/EventController.cs
using EventMenegmentAdmin.DTO;
using EventMenegmentDL.Entity;
using EventMenegmentSL.Services.Interfaces;
using EventMenegmentSL.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EventMenegmentAdmin.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IWebHostEnvironment _en;
        private readonly IGenericService<EventViewModel, Event> _generic;
        private readonly ILocationService _location;
        private readonly IOrganizerService _organizer;
        private readonly IEventTypeSevice _type;
        private readonly INotificationService _notificationService;
        private readonly UserManager<AppUser> _userManager;


        public EventController(IEventService eventService, IWebHostEnvironment en, IGenericService<EventViewModel, Event> generic, ILocationService location, IOrganizerService organizer, IEventTypeSevice type, INotificationService notificationService, UserManager<AppUser> userManager)
        {
            _eventService = eventService;
            _en = en;
            _generic = generic;
            _location = location;
            _organizer = organizer;
            _type = type;
            _notificationService = notificationService;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            var eventViewModels = await _generic.GetAllAsync();


            var eventDTOs = eventViewModels.Select(ev => new EventDTO
            {
                Id = ev.Id,
                Name = ev.Name,
                Description = ev.Description,
                Date = ev.Date,
                ImageUrl = ev.ImageUrl,
                EventTypeId = ev.EventTypeId,
                LocationId = ev.LocationId,
                OrganizerId = ev.OrganizerId,

            }).ToList();

            return View(eventDTOs);
        }



        public async Task<IActionResult> Details(int id)
        {
            var data = await _eventService.GetByIdEventWithIncludes(id);


            var eventDTO = new EventDTO
            {
                Id = data.Id,
                Name = data.Name,
                Description = data.Description,
                Date = data.Date,
                ImageUrl = data.ImageUrl,
                EventTypeId = data.EventTypeId,
                LocationId = data.LocationId,
                OrganizerId = data.OrganizerId,
                Participants = data.Participants,
                Organizer = data.Organizer,
                Location = data.Location,
                EventType = data.EventType



            };

            return View(eventDTO);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var organizers = await _organizer.GetAllAsync();
            var locations = await _location.GetAllAsync();
            var type = await _type.GetAllAsync();

            var viewModel = new EventDTO
            {
                Locations = locations.Select(m => new LocationViewModel
                {
                    Id = m.Id,
                    Name = m.Name
                }).ToList(),
                Organizers = organizers.Select(m => new OrganizerViewModel
                {
                    Id = m.Id,
                    Name = m.Name
                }).ToList(),
                EventTypes = type.Select(m => new EventTypeViewModel
                {
                    Id = m.Id,
                    Name = m.Name
                }).ToList()


            };

            return View(viewModel);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]

        public async Task<IActionResult> Create(EventDTO model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (!model.Image.ContentType.StartsWith("image/"))
            {
                ModelState.AddModelError("Image", "Please upload a valid image file.");
                return View(model);
            }

            if (model.Image.Length > 2 * 1024 * 1024)
            {
                ModelState.AddModelError("Image", "Image size must be less than 2MB.");
                return View(model);
            }

            var fileName = Guid.NewGuid() + Path.GetExtension(model.Image.FileName);
            var uploadsFolder = Path.Combine(_en.WebRootPath, "uploads");

            Directory.CreateDirectory(uploadsFolder);

            var filePath = Path.Combine(uploadsFolder, fileName);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await model.Image.CopyToAsync(stream);
            }

            var dto = new EventViewModel
            {
                Name = model.Name,
                Description = model.Description,
                Date = model.Date,
                EventTypeId = model.EventTypeId,
                LocationId = model.LocationId,
                OrganizerId = model.OrganizerId,
                Participants = model.Participants,
                ImageUrl = fileName
            };

            await _eventService.AddAsync(dto);
            var usrs =  _userManager.Users.ToList();
            foreach (var item in usrs)
            {
                if (string.IsNullOrWhiteSpace(item.Email))
                    continue;

                var token = await _userManager.GenerateUserTokenAsync(item, "Default", "EventNotification");
                var email = item.Email;
                var subject = "New Event Created";
                var message = $"A new event '{model.Name}' has been created. Check it out here: https://localhost:7232/Events";

                await _notificationService.SendToAllUsersAsync(email, subject, message);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _generic.GetByIdAsync(id);
            if (data == null)
            {
                return NotFound();
            }
            var organizers = await _organizer.GetAllAsync();
            var locations = await _location.GetAllAsync();
            var type = await _type.GetAllAsync();
            var viewModel = new EventDTO
            {
                Id = data.Id,
                Name = data.Name,
                Description = data.Description,
                Date = data.Date,
                ImageUrl = data.ImageUrl,
                EventTypeId = data.EventTypeId,
                LocationId = data.LocationId,
                OrganizerId = data.OrganizerId,
                Locations = locations.Select(m => new LocationViewModel
                {
                    Id = m.Id,
                    Name = m.Name
                }).ToList(),
                Organizers = organizers.Select(m => new OrganizerViewModel
                {
                    Id = m.Id,
                    Name = m.Name
                }).ToList(),
                EventTypes = type.Select(m => new EventTypeViewModel
                {
                    Id = m.Id,
                    Name = m.Name
                }).ToList()
            };
            return View(viewModel);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(EventDTO model)
        {
            if (!ModelState.IsValid)
                return View(model);
            if (model.Image != null && !model.Image.ContentType.StartsWith("image/"))
            {
                ModelState.AddModelError("Image", "Please upload a valid image file.");
                return View(model);
            }
            if (model.Image != null && model.Image.Length > 2 * 1024 * 1024)
            {
                ModelState.AddModelError("Image", "Image size must be less than 2MB.");
                return View(model);
            }
            var dto = new EventViewModel
            {
                Name = model.Name,
                Description = model.Description,
                Date = model.Date,
                EventTypeId = model.EventTypeId,
                LocationId = model.LocationId,
                OrganizerId = model.OrganizerId,
                Participants = model.Participants,
                Id = model.Id,
                ImageUrl = model.ImageUrl
            };

            if (model.Image != null)
            {
                var fileName = Guid.NewGuid() + Path.GetExtension(model.Image.FileName);
                var uploadsFolder = Path.Combine(_en.WebRootPath, "uploads");
                Directory.CreateDirectory(uploadsFolder);
                var filePath = Path.Combine(uploadsFolder, fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await model.Image.CopyToAsync(stream);
                }

                dto.ImageUrl = fileName;
            }

            await _eventService.UpdateAsync(dto);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return BadRequest("Invalid event ID.");
            }
            var result = await _generic.DeleteAsync(id);
            if (!result)
            {
                return NotFound("Event not found.");
            }
            return RedirectToAction("Index");
        }
    }
}

EventMenegmentUser/Controllers/EventTypeController.cs
using EventMenegmentDL.Entity;
using EventMenegmentSL.Services.Interfaces;
using EventMenegmentSL.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace EventMenegmentAdmin.Controllers
{
    public class EventTypeController : Controller
    {
        private readonly IEventTypeSevice _eventtyp;
        private readonly IGenericService<EventTypeViewModel, EventType> _genericService;

        public EventTypeController(IEventTypeSevice eventtyp, IGenericService<EventTypeViewModel, EventType> genericService)
        {
            _eventtyp = eventtyp;
            _genericService = genericService;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _eventtyp.GetAllEventTypeWithIncludes();
            return View(data);
        }


        public async Task<IActionResult> Edit(int id)
        {
            var data = await _genericService.GetByIdAsync(id);
            if (data == null)
            {
                return NotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EventTypeViewModel eventType)
        {
            if (!ModelState.IsValid)
            {
                return View(eventType);
            }
            var data = _eventtyp.UpdateAsync(eventType);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventTypeViewModel eventType)
        {
            if (ModelState.IsValid)
            {
                var createdEventType = await _eventtyp.AddAsync(eventType);
                if (createdEventType == null)
                {
                    return BadRequest("Failed to create event type.");
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventType);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _genericService.DeleteAsync(id);
            if (!result)
            {
                return NotFound();
            }
            return RedirectToAction("Index");
        }
    }
}

EventMenegmentUser/Controllers/RoleController.cs
using EventMenegmentAdmin.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EventMenegmentUI.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles.Select(r => new RoleViewModel
            {
                Id = r.Id,
                Name = r.Name
            }).ToList();
            return View(roles);


        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            ModelState.Remove("Id");
            if (ModelState.IsValid)
            {
                var role = new IdentityRole
                {
                    Name = model.Name
                };
                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

EventMenegmentUser/Controllers/UsersController.cs
using EventMenegmentAdmin.Models;
using EventMenegmentDL.Entity;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EventMenegmentAdmin.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager )
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var allUsers = _userManager.Users.ToList(); // Bütün istifadəçiləri çəkirik
            var usersInRole = new List<UserViewModel>();

            foreach (var user in allUsers)
            {
                var roles = await _userManager.GetRolesAsync(user);
           
                {
                    usersInRole.Add(new UserViewModel
                    {
                        Name = user.FullName,
                        Email = user.Email,
                        PhoneNumber = user.PhoneNumber,
                        Role = roles.ToList(),

                    });
                }
            }

            return View(usersInRole);
        }


        public async Task<IActionResult> AssignRole()
        {
           var users = await _userManager.Users.Select(u => new UserViewModel
            {
                Id = u.Id,
                Name = u.FullName,
              
            }).ToListAsync();
            var roles = await _roleManager.Roles.Select(r => new RoleViewModel
            {
                Id = r.Id,
                Name = r.Name
            }).ToListAsync();

           var model= new AssignRoleViewModel
            {
                Users = users,
                Roles = roles
            };
            return View(model);


        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AssignRole(AssignRoleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                ModelState.AddModelError("","User Not Found");
                return View(model);
            }
            var role = await _roleManager.FindByNameAsync(model.RoleName);
            if (role == null)
            {
                ModelState.AddModelError("", "Role Not Found");
                return View(model);
            }
            var result = await _userManager.AddToRoleAsync(user, role.Name);
            if (result.Succeeded)
            {
                return RedirectToAction("index");
            }
            else
            {
                return View(model);
            }

        }

     
    }
}

EventMenegmentUser/Views/Shared/_Footer.cshtml
<footer class="sticky-footer bg-white">
	<div class="container my-auto">
		<div class="copyright text-center my-auto">
			<span>Copyright &copy; Your Website 2021</span>
		</div>
	</div>
</footer>
<!-- End of Footer -->
			</div>
<!-- End of Content Wrapper -->
		</div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
	<i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
	 aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
			<div class="modal-footer">
				<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
				<a class="btn btn-primary" href="login.html">Logout</a>
			</div>
		</div>
	</div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom s~/cripts for all pages-->
<script src="~/js/sb-admin-2.min.js"></script>

<!-- Page lev~/el plugins -->
<script src="~/vendor/chart.js/Chart.min.js"></script>

<!-- Page lev~/el custom scripts -->
<script src="~/js/demo/chart-area-demo.js"></script>
<script src="~/js/demo/chart-pie-demo.js"></script>

EventMenegmentUser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"] - Admin Panel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/admin.css" rel="stylesheet" />
</head>
<body>
    <partial name="_Navbar" />

    <div class="d-flex">

        <partial name="_Sidebar" />
        <div class="p-4 w-100">
            @RenderBody()
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

EventMenegmentUser/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom shadow-sm">
    <div class="container-fluid">
        <a class="navbar-brand text-primary fw-bold" href="/">EventX</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
           
        </div>
    </div>
</nav>

EventMenegmentUser/Views/Shared/_Sidebar.cshtml
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light vh-100 shadow-sm" style="width: 250px;">
	<a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
		<span class="fs-4 text-primary fw-bold">Admin Panel</span>
	</a>

<ul style="text-decoration:none">
   

	<li class="nav-item mb-3" >
			<a class="nav-link collapsed mt-2"asp-controller="Event" asp-action="Index" data-toggle="collapse" data-target="#collapseBook"
		   aria-expanded="true" aria-controls="collapseBook">
			<i class="fas fa-book"></i>
			<span>Events</span>
		</a>
		
	
	</li>
		@if (User.IsInRole("Admin"))
		{
			<li class="nav-item mb-3">
				<a class="nav-link collapsed mt-2" asp-controller="EventType" asp-action="Index" data-toggle="collapse" data-target="#collapseBook"
				   aria-expanded="true" aria-controls="collapseBook">
					<i class="fas fa-book"></i>
					<span>EventTypes</span>
				</a>


			</li>
		}

		@if (User.IsInRole("Admin"))
		{
		
		<li class="nav-item mb-3">
			<a class="nav-link collapsed mt-2"asp-controller="Location" asp-action="Index" data-toggle="collapse" data-target="#collapseBook"
		   aria-expanded="true" aria-controls="collapseBook">
			<i class="fas fa-book"></i>
			<span>Locations</span>
		</a>

	
	
	</li>
		}
		<li class="nav-item mb-3">
			<a class="nav-link collapsed mt-2"asp-controller="Organizer" asp-action="Index" data-toggle="collapse" data-target="#collapseBook"
		   aria-expanded="true" aria-controls="collapseBook">
			<i class="fas fa-book"></i>
			<span>Organizer</span>
		</a>

	
	
	</li>
	
	@if (User.IsInRole("Admin"))
		{
		
	
		<li class="nav-item mb-3">
			<a class="nav-link collapsed mt-2"asp-controller="Role" asp-action="Index" data-toggle="collapse" data-target="#collapseBook"
		   aria-expanded="true" aria-controls="collapseBook">
			<i class="fas fa-book"></i>
			<span>Roles</span>
		</a>

	
	
	</li>
		}
	</li>
	
		<li class="nav-item mb-3">
			<a class="nav-link collapsed mt-2"asp-controller="Users" asp-action="Index" data-toggle="collapse" data-target="#collapseBook"
		   aria-expanded="true" aria-controls="collapseBook">
			<i class="fas fa-book"></i>
			<span>Users</span>
		</a>

	
	
	</li>
	
	</li>
	
		<li class="nav-item mb-3">
			<a class="nav-link collapsed mt-2" asp-controller="Invitation" asp-action="Create" data-toggle="collapse" data-target="#collapseBook"
		   aria-expanded="true" aria-controls="collapseBook">
			<i class="fas fa-book"></i>
			<span>Inivitations</span>
		</a>

	
	
	</li>
	

 
	






	

</ul>
</div>